# Generated by Django 4.2.6 on 2023-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(null=True),
        ),
    ]
